name: "Pre-release"

on:
  push:
    branches:
      - "*"

env:
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

jobs:
  pre-release:
    name: "Build and Pre-release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Jar file
        run: ./gradlew clean build shadowJar
      - name: Upload to Modrinth
        run: ./gradlew modrinth
